name: Daily Data Update

on:
  schedule:
    # Ejecutar todos los días a las 9:00 AM (UTC, ajustar según zona horaria)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  update_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper and update data
        env:
          FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
        run: |
          python scraping/daily_pipeline.py
        id: run_scraper
        continue-on-error: false
      
      - name: Verificar resultados
        run: |
          if [ -f "logs/pipeline_error.log" ]; then
            echo "::error::Error en el pipeline. Revisar archivo de log"
            exit 1
          fi
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/ logs/
          git commit -m "Update data: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
